title: Myo Min Thu - Security
description: > # this means to ignore newlines until "baseurl:"
  I am bug bounty hunter from myanmar
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Myo Min Thu # add your name
author-img: profile.jpg # add your photo
about-author: I am a bug bounty hunter<br><b>HOF Lists<b><br><a href="#">Google</a><br>Facebook<br> # add description
social-twitter: kolayma_mmt # add your Twitter handle
social-facebook: godofdarkness.msf # add your Facebook handle
social-github: nightmare-sec # add your Github handle
social-email: kolayma@protonmail.com # add your Email address

# Disqus
discus-identifier: Freedom # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
