title: Myo Min Thu - Security
description: > # this means to ignore newlines until "baseurl:"
  I am bug bounty hunter from myanmar
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Myo Min Thu # add your name
author-img: profile.jpg # add your photo
about-author: I am a bug bounty hunter<br><br><br>Hall Of Fame<br><br><a target="_blank" href="https://bughunter.withgoogle.com/profile/40b3c633-09ea-476e-b09f-ec00237029c3" style="text-decoration:none">Google</a><br><a target="_blank" href="https://hackerone.com/mailru/thanks/2020?type=team" style="text-decoration:none">Mail.ru</a><br><a target="_blank" href="https://hackerone.com/gitlab" style="text-decoration:none">Gitlab</a><br><a target="_blank" href="https://hackerone.com/dropbox" style="text-decoration:none">Dropbox</a><br><a target="_blank" href="https://hackerone.com/nightmare_msf" style="text-decoration:none">Others</a><br> # add description
social-twitter: kolayma_mmt # add your Twitter handle
social-facebook: godofdarkness.msf # add your Facebook handle
social-github: nightmare-sec # add your Github handle
social-email: kolayma@protonmail.com # add your Email address

# Disqus
discus-identifier: Freedom # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
